dist: trusty
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
  sonarcloud:
    organization: "zephyrj-github"
    token:
      secure: "t2nQ3mCwW0XHTpiq+yQCFmxg/1w/UbOm7hNNtFZJb98KHCrYI7XFRAi6dG0Uwsc/q+Zim40AGLt3pGZTMC2LmRhXLBJ/ozXI1QDZyJY6iJMruLOfOJNG/1FkonPkPeiQPH5uWPlKvO7o5PYNLSCyyNjzlcTZlXGIBKzZUXu5X438HgLB2lEbZ4+dhBbzuuudM+2lDyAS6XlExRu23hMi/ceZ3NdUUKBUzcyidby6x3l3VkVpYYvdQZegR+pCRhQ/KyDu4zn03t67QyL9m5dSkPL7a6mWd5c6U94uzgTsfFvpJTvcPByvBpDi+Q421AY3r+9v2+dhR67U5QuYITMiRQIlQqhRALrVhw5MXtIFnzy7Jnvgt3fD7a0HjW6FeIzuZxL4GbGiERQvLNKesat99YGQPvO8A4rkHXCd4VP7umzUY+s+HjA2iw7XS1LfFGHI4DspYjsS9bruoWgryADfIAYhRfAgYwKWEhUBB+WX6XrBUeTI4+/7EuJx4tB8TQO92f1gN49j38fJb3AU9zjrIkKDeH4sLSsMpom4xom72gYEbWOlLXhY2Viy9a5YL/XEdmA24ZZ9jpHdm6HxCpdVIYxRk3v871anqD+7g5k/+M/oIxR4D4H6JCYKRngTQHUBCQ98+6D7TCdjSrQWtwHCaoy4bpTyOLbIHFZf5jaJm2E="

before_script:
- sudo apt-get update -qq
- sudo apt-get install libboost-thread-dev libboost-system-dev libprotobuf-dev protobuf-compiler
script:
- export CC=gcc-7
- export CXX=g++-7
- mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make && make test
- cd .. && sonar-scanner
