dist: trusty

language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-thread-dev libboost-system-dev libprotobuf-dev protobuf-compiler

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make