language: cpp

matrix:
  include:
# works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-tes
            - llvm-toolchain-trusty-5.0
            - sourceline: 'ppa:nschloe/cmake-nightly'
          packages:
            - g++-7
            - clang-5.0
            - cmake-3.10

compiler:
  - clang
  - gcc

before_script:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get update -qq
    - sudo apt-get install libboost-thread-dev libboost-system-dev
    - mkdir build
    - cd build
    - cmake ..

script: make